In [1]:
import numpy as np
import sys

sys.setrecursionlimit(110000) # change the recursion depth

#l=0.1 #lamda


In [2]:
#  sigmoid(logistic) function
def mathf(x):
    return 1/(1+np.exp(-x))


In [3]:
# result of each preceptron
def ptronV(xList,wList):
    result=np.sum(np.multiply(xList,wList))

    return mathf(result)


In [4]:
# train the weights
def trainW(xList, tList, oList, hidResults, wList1, wList2, n, m, T):

    # Backward
    # Hidden Layer weight list 2
    deltaOList2 = (tList - oList) * (oList * (1 - oList))
    #deltaWLists = np.empty(m)
    deltaWLists2 = np.empty(m)
    deltaWLists = hidResults @ deltaOList2
    for i in range(0,n):
        deltaWLists2[i]=np.sum(hidResults[i])*deltaOList2[i]

    print(hidResults)
    print(deltaOList2)
    print(deltaWLists2)
    print(deltaWLists)
    #deltaWLists=np.dot(hidResults,deltaOList2)
    newWList2 = wList2 + deltaWLists2

    # Hidden Layer weight list 1
    deltaHList1=np.empty([n,m])
    for i in range(0,n):
        deltaHList1[i]=deltaOList2[i]*wList2[i]*(hidResults[i]*(1-hidResults[i]))
    deltaHList1 = np.mat(deltaHList1)
    xList = np.mat(xList)
    deltaWLists1 = np.dot(deltaHList1, xList)
    newWList1 = wList1 + deltaWLists1

    # forward
    newHidLists=np.empty([n,m])
    newOList=np.empty(n)
    for i in range(0, n):
        for j in range(0, m):
            newHidLists[i][j] = ptronV(xList[i], newWList1[i])  #Hidden layer preceptron
        newOList[i] = ptronV(hidResults[i], newWList2[i])   # Output preceptron

    errors=np.sum(abs(tList-newOList))
    print(T, errors, newOList)
    if T==0 or errors<0.01:
        print('Target: ', tList)
        print('Weights 0-11(X[i,j]):', newWList1)
        print('Weights 12-15:', newWList2)
        return T

    # recursion loop
    return trainW(xList, tList, newOList, newHidLists, newWList1, newWList2, n, m, T-1)


In [5]:
def main():
    xList = [[1,0,0],[1,0,1],[1,1,0],[1,1,1]]   # input, bias set to 1
    tList=[0,1,1,0]     # target output
    n=len(xList)
    m=4         # number of hidden preceptrons
    hidResults=np.empty([n,m])  # value of hiden preceptrons for each input
    oList=np.empty(n)       # output value by training

    wList1=np.empty([n,3])     # first level weights
    wList2=np.empty(m)      # second level weights

    # 1st Forward (weights are random values)
    wList2 = np.random.rand(m)
    for i in range(0,n):
        for j in range(0,m):
            wList1[i] = np.random.rand(3)
            hidResults[i][j] = ptronV(xList[i],wList1[i])
        oList[i]=ptronV(hidResults[i],wList2)

    T=2  # times of training. this laptop environment can train at most 3900 times
    print('Start: ', oList)
    print('Times    Errors  OutputList')
    trainW(xList, tList, oList, hidResults, wList1, wList2, n, m, T)


if __name__ == '__main__':
    main()



Start:  [ 0.84102106  0.8699394   0.87876467  0.9124622 ]
Times    Errors  OutputList
[[ 0.55510566  0.53347601  0.67218952  0.55724533]
 [ 0.71345601  0.67184403  0.66573097  0.63335345]
 [ 0.66921209  0.77600419  0.72172941  0.66415101]
 [ 0.85770008  0.76923693  0.86534731  0.78679334]]
[-0.11244842  0.01471568  0.01291609 -0.07288286]
[-0.26065729  0.03950256  0.03656669 -0.23898856]
[-0.08650186 -0.10790233 -0.10291571 -0.13129402]
2 1.89900539927 [ 0.77776182  0.77626508  0.93118697  0.82869562]
[[ 0.53575185  0.53575185  0.53575185  0.53575185]
 [ 0.63528142  0.63528142  0.63528142  0.63528142]
 [ 0.66730775  0.66730775  0.66730775  0.66730775]
 [ 0.77592148  0.77592148  0.77592148  0.77592148]]
[-0.13443486  0.03885775  0.00440939 -0.11764096]
[-0.28809491  0.09874242  0.01176967 -0.36512059]
[-0.11186964 -0.13265228 -0.13933966 -0.16201915]
1 1.49080351457 [ 0.63197643  0.80667656  0.92326372  0.58876736]
[[ 0.51773602  0.51773602  0.51773602  0.51773602]
 [ 0.64106202  0.6410